# Build
FROM node:20-bookworm-slim AS builder


WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY tsconfig.json ./
COPY src ./src

RUN npm run build


# Runtime
FROM node:20-bookworm-slim AS runner

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev && apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/dist ./dist

# LiveKit + app env vars
ENV GCP_SPEECH_LANGUAGE="en-US"
ENV WEBAPP_URL="http://host.docker.internal:3000"

EXPOSE 8080

CMD ["node", "dist/index.js"]